---
title: Spectre
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _pages
  values:
    permalink: "/:basename:output_ext"
baseurl: ''
url: ''
markdown: kramdown
permalink: pretty
plugins:
- jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings:
  - html
  - head
  - body
include:
- _pages
sass:
  sass_dir: assets/scss
  style: compressed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE.text
- README.md
- SECURITY.md
